### ISSUE TITLE
silent error if a CDX entry does not exists in the warc path

### ISSUE THREAD

**Issue by dportabella** [helgeho/ArchiveSpark#10]
```
val rdd: RDD[WarcRecord] = ArchiveSpark.load(sc, WarcCdxHdfsSpec(cdxPath = "/data/example.cdx.gz", warcPath = "/tmp/empty_directory"))
rdd.foreach(println)
```

in this case, the `warcPath` is an empty directory, so no entries from the CDX file will be found. The issue is that `rdd.foreach` will silently ignore this problem.

Shouldn't it throw an error? or is there a way to force to throw an error or warning?

**Comment by helgeho** [comment]
This is due to the way the DataSpec is implemented and not a limitation of ArchiveSpark. The DataSpec internally creates a map of all available WARC files and if a CDX files does not match, it simply skips it, as it assumes that your CDX records match the WARC files that you want to work with. If you need to check for existence, please feel free to create a project in which you copy the WarcCdxHdfsSpec and modify it so that it throws an error in that case.

**Comment by dportabella** [comment]
ok.

**Comment by helgeho** [comment]
We now have instructions on how to create DataSpecs:
https://github.com/helgeho/ArchiveSpark/blob/master/docs/Dev_DataSpecs.md
