### ISSUE TITLE
Missing location (offset/filename) in CDX generated from uncompressed WARC

### ISSUE THREAD

**Issue by xw0078** [helgeho/ArchiveSpark#14]
Hi,
I am trying to load WARC/CDX on my Mac file system through:
`val records = ArchiveSpark.load(WarcCdxHdfsSpec(cdxPath, warcPath))`
I created the CDX file through `warc.saveAsCdx` by following your "Generate_CDX.ipynb
" example. 

But I always get zero count for the records. Any idea where did I possibly go wrong?

**Comment by helgeho** [comment]
Hi and thanks for using ArchiveSpark!
Do you have only one or multiple (W)ARC files? What's the name of the file if it's only one?
Did you check in the generated CDX file(s) whether they points to the right (W)ARC files?
Please note that `WarcCdxHdfsSpec` takes a directory as (W)ARC path, not a file name, as the filenames are containes in the CDX records.
If possible, please post the first line of your generated CDX file(s) here.

**Comment by helgeho** [comment]
Also, you could try to load only the CDX files, using the `CdxHdfsSpec` (see [DataSpecs](https://github.com/helgeho/ArchiveSpark/blob/master/docs/DataSpecs.md), and count the records to see if the problem is has to do with the mapping between CDX and (W)ARC or already with the CDX files.

**Comment by xw0078** [comment]
Thanks for the reply.

I am aware of `WarcCdxHdfsSpec ` is taking of warcPath as one directory. In my case, I only have one file in warcPath and 1 file in cdxPath. My first try was to load WARC with CDX file created through CDXJ-indexer, which follows the format "CDX N b a m s k r M S V g". 
As I don't get the count number, I followed exact the same steps as in "Generate_CDX.ipynb" to get corresponding CDX file and I still get 0 count. 

And I notice that the output cdx file from `warc.saveAsCdx` does not contain warc file name.
My original CDX:
`com,biography)/people/seung-hui-cho-235991 20170328165259 http://www.biography.com/people/seung-hui-cho-235991 text/html 200 NSEZCE2K3EMRRJF6VXPBNY6GXUQLIE6M - - 45271 0 Virginia-Tech-Shooting_20070416-copy.warc` 
Generated CDX from `warc.saveAsCdx`:
`com,biography)/people/seung-hui-cho-235991 20170328165259 http://www.biography.com/people/seung-hui-cho-235991 text/html 200 BUBXYQ65JZ6KDTSZYLJUDF3LVF3FOO5K - - 45805`

Following are my test code:
I have input files locate in following paths:
`/Users/Xinyue/ArchiveSpark_Project/data/7910_data/warc/my-collection.warc`
`/Users/Xinyue/ArchiveSpark_Project/data/7910_data/cdx/my-collection.cdx`

I used the following scripts in spark-shell:

```scala
val warcPath = "/Users/Xinyue/ArchiveSpark_Project/data/7910_data/warc"
val cdxPath = "/Users/Xinyue/ArchiveSpark_Project/data/7910_data/cdx/my-collection.cdx"
val records = ArchiveSpark.load(WarcCdxHdfsSpec(cdxPath, warcPath))
records.count // get 0 here
```
By following "Generate_CDX.ipynb", I have:
`/Users/Xinyue/ArchiveSpark_Project/data/7910_data/test/warc/my-collection.warc`

```scala
val path = "/Users/Xinyue/ArchiveSpark_Project/data/7910_data/test/"
val warcPath = path + "/warc"
val warc = ArchiveSpark.load(WarcHdfsSpec(warcPath + "/*.*arc*"))
warc.count // this works
warc.saveAsCdx(path + "_cdx.gz")
val records = ArchiveSpark.load(WarcCdxHdfsSpec(path + "_cdx.gz", warcPath))
records.count // get 0 here
```

**Comment by xw0078** [comment]
I got it work with a gz compressed warc file, I think this might be the issue?

**Comment by helgeho** [comment]
Yes, that's the issue. The problem is that reader in the `WarcHdfsSpec` does not provide us positional information and so you cannot generate suitable CDX files from this spec. There is also a note about that in the [notebook](https://github.com/helgeho/ArchiveSpark/blob/master/notebooks/Generate_CDX.ipynb): *While with `WarcGzHdfsSpec` CDX files with positional information can directly be generated using `.saveAsCdx`, with `WarcHdfsSpec` the whole dataset has to be saved along with CDX records using `.saveAsWarc(..., generateCdx = true)`, therefore `WarcGzHdfsSpec` is highly recommended if it suits your dataset (see below):*.

So if you do not have suitable .(w)arc.gz files, i.e., files where every record is compressed individually, please first create such files using `saveAsWarc`, which will in the same step generate CDX files for you as well. However, if you already have (W)ARC files in this format, `WarcGzHdfsSpec` is the recommended way to go and everything will work.

Regarding your original CDX records, in my opinion these look perfectly fine, except that the WARC filename does not match. So if you rename your WARC file to `Virginia-Tech-Shooting_20070416-copy.warc`, these should work as well without generating any new (W)ARC or CDX files.

Hope this helps!
