### ISSUE TITLE
broken link in the doc

### ISSUE THREAD

**Issue by dportabella** [helgeho/ArchiveSpark#2]
this link is broken:
https://github.com/helgeho/ArchiveSpark/wiki/Getting-Started
->  WebSci'16 Hackathon -> Example notebook

**Comment by rjoberon** [comment]
on the same page the link to https://github.com/helgeho/ArchiveSpark/wiki/notebooks is also broken.

**Comment by helgeho** [comment]
Thanks for the hints! We are actually aware of the problems in the documentation, it's not just the broken links, but large parts that need to be refactored. The concrete issues you pointed out are caused by 1. moving the documentation into the wiki, which broke the relative links, and 2. notebooks which got outdated with the introduction of dataspecs and other features and need to be slightly changed to make them work again, thus we moved them into a 'legacy' folder: https://github.com/helgeho/ArchiveSpark/tree/master/notebooks/legacy

More up-to-date and working notebooks can be found in related projects:
https://github.com/helgeho/MHLonArchiveSpark/blob/master/examples/MhlPolioSymptomsSearch.ipynb
and
https://github.com/helgeho/ArchiveSpark2Triples/blob/master/notebooks/Triples.ipynb

We are planning to restructure and rewrite the whole documentation very soon and also extend it with a complete reference of the available features / operations, that's currently in progress. So please stay tuned and if you have questions before, please get in touch. Thanks!

**Comment by dportabella** [comment]
wow, thanks for the examples! :)

**Comment by helgeho** [comment]
The wiki / our old documentation has been shutdown and replaced by a new, proper documentation:
https://github.com/helgeho/ArchiveSpark/blob/master/docs/README.md

Finally, we also have a whole list of recipes / examples:
https://github.com/helgeho/ArchiveSpark/blob/master/docs/Recipes.md
