### ISSUE TITLE
 How to get the Array[Byte] from the InputStream in ArchiveSpark3 efficiently

### ISSUE THREAD

**Issue by parismic** [helgeho/ArchiveSpark#22]
I have sufficiently clean data, but unfortunately calling the input stream throws hasNext exceptions during run-time. Could this be a bug? 

```
val InStreamRDD = WarcRDD.map{record => bytes(record.access{_.payload})}
InStreamRDD.saveAsObjectFile(someLocation)
```

I need the input stream to increase the speed of my transformations. Any ideas?

**Comment by helgeho** [comment]
It is impossible to save an open input stream, since an instance of `InputStream` constitutes just a pointer to some open byte stream. A possible way to store that data would be storing the raw bytes by writing the stream into a byte array first. If that's what your `bytes(...)` method is meant to do, you will need to move it inside the `record.access` call, as `.access` automatically closes the input stream, e.g., `record.access(r => bytes(r.payload))`. Hope this helps!

**Comment by parismic** [comment]
Thanks. I think it was a mistake on my part. It seemed that `record.access(r => r.payload):InputStream` would be the proper way to interact with the  InputStream, since both `record: WarcRecord` and `r: WarcRecord` are the same type.

**Comment by helgeho** [comment]
In fact, it is not the same type, `record` is of type `org.archive.archivespark.specific.warc.WarcRecord` and `r` is of type `org.archive.archivespark.sparkling.warc.WarcRecord`. This is a results of the integration with parts of Sparkling, our internal data-processing library at IA, with ArchiveSpark 3.0.
