### ISSUE TITLE
WARCType metadata

### ISSUE THREAD

**Issue by parismic** [helgeho/ArchiveSpark#25]
Each WARC record has 3 subsection, **response, request, metadata.** 
How can I _access_ each individual subsection? 

It seems that ArchiveSpark returns **only** the **response** subsection or am I mistaken?

Thanks

**Comment by helgeho** [comment]
Hey Michael,

These are all considered separate records with their type being specified in the `WARC-Type` header. CDX records do not reflect types other than `response` and `revisit`, which is why originally ArchiveSpark did only support those.

However, when you load an archive directly from WARC files (`WarcSpec.fromFiles` -- https://github.com/helgeho/ArchiveSpark/blob/master/src/main/scala/org/archive/archivespark/specific/warc/WarcSpec.scala#L39) you can set `includeOthers = true` in order to include `request` + `metadata` records as well.

(All this is part of the underlying _Sparkling_ library, which is pretty outdated in this repo -- I'll push a newer version with the most recent updates and bugfixes ASAP, in case you're encountering any issues with that ☝️)

Hope this helps!

**Comment by parismic** [comment]
Hi Helge,
thanks for the quick reply! There is a problem though:

If you want to work with a Heritrix created WARCFile.gz containing WARC-Records there is a problem loading these files in [this](https://github.com/helgeho/ArchiveSpark/blob/master/src/main/scala/org/archive/archivespark/sparkling/warc/WarcRecord.scala#L72) line. 

There are, if I recall correctly 6 different WARC types, some of which do not have a proper "warc-target-uri", which is why the suggested approach returns

```
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at org.archive.archivespark.sparkling.warc.WarcRecord.toCdx(WarcRecord.scala:72)
```
This might need a fix.
Best,
Micha

**Comment by helgeho** [comment]
You're right, that's actually on of the things that's been fixed in _Sparkling_ for quite some time already -- give me a few days and I'll pull over the latest code from it.

**Comment by parismic** [comment]
Hi Helge,
are there any news on this issue?

**Comment by helgeho** [comment]
Not yet, but I'm almost on it, sorry about the delay!

**Comment by helgeho** [comment]
Done, all contained Sparkling modules have been updated

**Comment by parismic** [comment]
Thanks! I'll check it ASAP.
